<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="tr100testts01" name="telia.testautomation.Revise.Sprint3_Xdsl_Revise" tests="3" failures="0" timestamp="13 Mar 2019 13:20:24 GMT" time="313.857" errors="1">
  <testcase name="xDSL_Revise_Modify" time="159.786" classname="telia.testautomation.Revise.Sprint3_Xdsl_Revise"/>
  <testcase name="xDSL_Revise_New" time="3.936" classname="telia.testautomation.Revise.Sprint3_Xdsl_Revise">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at telia.testautomation.Revise.Sprint3_Xdsl_Revise.xDSL_Revise_New(Sprint3_Xdsl_Revise.java:195)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </error>
  </testcase> <!-- xDSL_Revise_New -->
  <testcase name="xDSL_Revise_Disconnect" time="150.135" classname="telia.testautomation.Revise.Sprint3_Xdsl_Revise"/>
</testsuite> <!-- telia.testautomation.Revise.Sprint3_Xdsl_Revise -->
